add null check to writeValue
ngneat/input-mask pull request #17
Opened 2021-08-24 16:08 UTC by aceleghin

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ X ] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[X ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

There is no check in the writeValue method, so when the field is null there is an error as I mentioned in the issue.
Issue Number: [#6 ](https://github.com/ngneat/input-mask/issues/6)

## What is the new behavior?
Simply adding a null check to writeValue method solves the issue.

## Does this PR introduce a breaking change?

```
[ ] Yes
[ X ] No
```

## Other information

2021-08-25 06:15 UTC, shhdharmen requested changes

2021-08-25 06:15 UTC, shhdharmen commented on projects/ngneat/input-mask/src/lib/input-mask.directive.ts
> +    }
Please `else` block.

2021-08-31 17:54 UTC, drenda commented on projects/ngneat/input-mask/src/lib/input-mask.directive.ts
> +    }
Any news on this PR?

2021-08-31 17:55 UTC, drenda commented
Any news on this PR?

2021-09-01 06:15 UTC, shhdharmen commented
> Any news on this PR?

As I have already mentioned, commit messages do not follow guidelines.

2021-09-01 09:08 UTC, shhdharmen commented
Everything is already mentioned in contribution guidelines.

> After staging your files, commit them using `npm run commit`

2021-09-14 11:33 UTC, shhdharmen commented
@aceleghin are you working on this PR?

2021-09-14 13:34 UTC, aceleghin commented
I have already correct it in my fork because I need it in production. For me, the comment is correct, unfortunately, you don't merge it but your library does not work without this fix.

2021-09-14 14:37 UTC, closed without merging