Fix error when filed is empty and valid
ngneat/input-mask pull request #18
Opened 2021-08-24 16:22 UTC by aceleghin

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ X ] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ X ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

The field now has an error like `{ inputMask: false }` also if it is empty and valid.

Issue Number: [#12](https://github.com/ngneat/input-mask/issues/12)

## What is the new behavior?
Now there is a check to avoid to set error if the field is valid and empty.

## Does this PR introduce a breaking change?

```
[ ] Yes
[ X ] No
```

## Other information

2021-08-25 06:18 UTC, shhdharmen requested changes

2021-08-25 06:18 UTC, shhdharmen commented on projects/ngneat/input-mask/src/lib/input-mask.directive.ts
> +    return isEmptyValue ||
Please check return type, it should be: `{ [key: string]: any } | null`

2021-08-31 17:55 UTC, drenda commented on projects/ngneat/input-mask/src/lib/input-mask.directive.ts
> +    return isEmptyValue ||
Any news on this PR?

2021-08-31 17:55 UTC, drenda commented
Any news on this PR?

2021-09-01 06:12 UTC, shhdharmen approved these changes
LGTM

2021-09-14 11:33 UTC, shhdharmen commented
@aceleghin are you working on this PR? Tests are failing.

2021-09-14 13:29 UTC, aceleghin commented
Hi, no sorry, I have already invested time to correct the bug, I don't use spectator so I can't fix it.

2021-09-14 16:06 UTC, closed without merging