fix(schematics): fix typo in ng-module-imports.ts
ngneat/input-mask pull request #25
Opened 2021-09-18 11:16 UTC by eltociear

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our [guidelines](./CONTRIBUTING.md#commit).
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information
specifed -> specified

2021-09-18 15:43 UTC, shhdharmen approved these changes

2021-09-18 15:48 UTC, shhdharmen requested changes
As this is not a bug fix and only a typo fix in comment, it should have `docs` in commit message and not `fix`. Please change your commit message.

2021-09-18 16:15 UTC, eltociear commented
@shhdharmen Thx! I changed it!

2021-09-18 16:59 UTC, shhdharmen approved these changes

2021-09-18 17:02 UTC, merged

2021-09-21 11:10 UTC, shhdharmen commented
:tada: This PR is included in version 3.0.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@ngneat/input-mask/v/3.0.2)
- [GitHub release](https://github.com/ngneat/input-mask/releases/tag/v3.0.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: