feat: upgrade to Angular 13 and support modern package format
ngneat/input-mask pull request #39
Opened 2021-11-07 19:37 UTC by arturovt

2021-11-11 06:53 UTC, shhdharmen requested changes
As this will be a breaking change, please fix commit message.

2021-11-11 06:53 UTC, shhdharmen commented on projects/ngneat/input-mask/package.json
> +    "@angular/core": ">=13.0.0",
We need to keep support from v11.

2021-11-11 16:57 UTC, arturovt commented on projects/ngneat/input-mask/package.json
> +    "@angular/core": ">=13.0.0",
The current input-mask version is compatible with Angular 11 & 12. The APF (Angular Package Format) with `.mjs` files is not backwards-compatible with older versions of Angular since it's been released with Angular 13.

2021-11-11 18:11 UTC, shhdharmen commented
As we are using semantic-release, you will need to include "Breaking Change" in commit message.

Run `npm run commit` and make sure select yes for breaking change.

2021-11-11 18:22 UTC, arturovt commented
@shhdharmen hey. I've amended the commit message, could you check if it follows the semantic release?

2021-11-12 06:03 UTC, shhdharmen approved these changes

2021-11-12 06:11 UTC, shhdharmen commented
@arturovt thanks for the changes! Can you please add version compatibility table after "Features" section in the README? Something like below:

## Version check

| @ngneat/input-mask | Angular |
| - | - |
| 3.x | >= 11.2.7 < 13 |
| 4.x | >= 13 |

2021-11-12 11:07 UTC, shhdharmen approved these changes
LGTM

2021-11-12 13:51 UTC, merged

2021-11-12 13:53 UTC, shhdharmen commented
:tada: This PR is included in version 4.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@ngneat/input-mask/v/4.0.0)
- [GitHub release](https://github.com/ngneat/input-mask/releases/tag/v4.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: