Implement setDisabledState to disable the input
ngneat/input-mask pull request #47
Opened 2021-11-15 21:20 UTC by ssougnez

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our [guidelines](./CONTRIBUTING.md#commit).
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Disabling a control using a formGroup does not work.

Issue Number: 46 (https://github.com/ngneat/input-mask/issues/46)

## What is the new behavior?

Disabling the input using a formGroup disables the input (as expected)

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

I didn't update the doc as the behavior is expected.
I did test the change by modifying the app component but I reverted these changes.

2021-11-16 06:19 UTC, shhdharmen commented on projects/ngneat/input-mask/src/lib/input-mask.directive.ts
> +      this.nativeInputElement.disabled = isDisabled;
Use `renderer` to set `disabled`. Ref: https://angular.io/api/forms/ControlValueAccessor#setDisabledState-usage-notes

2021-11-16 06:21 UTC, shhdharmen requested changes
1. Commit messages do not follow [guidelines](https://github.com/ngneat/input-mask/blob/main/CONTRIBUTING.md#-commit-message-guidelines).
2. Use `renderer` to set `disabled`. Ref: https://angular.io/api/forms/ControlValueAccessor#setDisabledState-usage-notes

2021-11-16 09:42 UTC, ssougnez commented
Sorry but I'm a bit new in the pull request world haha
I just commit/push the changes you asked on my branch, do I have to do anything for you to view the changes or is it automatic?

Thanks

2021-11-17 09:55 UTC, shhdharmen commented
Your branch still has non-compliant commit messages. Please fix. Either you will have to make the changes again and do force push with proper commits or create a new PR.

2021-11-17 09:59 UTC, ssougnez commented
Okay.
I'm closing this PR and I'll make a new one ;-)

2021-11-17 09:59 UTC, closed without merging